auth:
  api-key:
    secret: ${SECALE_API_KEY_SECRET:5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b}
  email:
    enable: ${SECALE_EMAIL_AUTH_ENABLED:true}
    enable-register: ${SECALE_EMAIL_SIGNUP_ENABLED:true}
  workspace-creation: ${SECALE_CREATE_WORKSPACE_ON_SIGNUP:true}

spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: false
      uri: ${SECALE_MONGODB_URL:mongodb://lowcoder:secret123@mongodb:27017/lowcoder?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256}
    redis:
      url: ${SECALE_REDIS_URL:redis://redis:6379}
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false
  codec:
    max-in-memory-size: 20MB
  webflux:
    base-path: /
  mail:
    host: ${SECALE_ADMIN_SMTP_HOST:localhost}
    port: ${SECALE_ADMIN_SMTP_PORT:587}
    username: ${SECALE_ADMIN_SMTP_USERNAME:info@localhost}
    password: ${SECALE_ADMIN_SMTP_PASSWORD:s3cr3t}
    properties:
      mail:
        smtp:
          auth: ${SECALE_ADMIN_SMTP_AUTH:true}
          ssl:
            enable: ${SECALE_ADMIN_SMTP_SSL_ENABLED:false}
            checkserveridentity: false
          starttls:
            enable: ${SECALE_ADMIN_SMTP_STARTTLS_ENABLED:true}
            required: ${SECALE_ADMIN_SMTP_STARTTLS_REQUIRED:true}
        transport:
          protocol: smtp
  mvc:
    pathmatch:
      trailing-slash-match: true
server:
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  http2:
    enabled: true
  port: 8080
  shutdown: graceful

default:
  orgs-per-user: ${SECALE_MAX_ORGS_PER_USER:100}
  org-member-count: ${SECALE_MAX_MEMBERS_PER_ORG:1000}
  org-group-count: ${SECALE_MAX_GROUPS_PER_ORG:100}
  org-app-count: ${SECALE_MAX_APPS_PER_ORG:1000}
  developer-count: ${SECALE_MAX_DEVELOPERS:50}
  api-rate-limit: ${SECALE_API_RATE_LIMIT:50}
  query-timeout: ${SECALE_DEFAULT_QUERY_TIMEOUT:10}

common:
  cookie-name: ${SECALE_COOKIE_NAME:SECALE_CE_SELFHOST_TOKEN}
  product: lowcoder
  domain:
    default-value: lowcoder.org
  cloud: false
  version: 0.0.1
  apiVersion: 1.2
  block-hound-enable: false
  encrypt:
    password: ${SECALE_DB_ENCRYPTION_PASSWORD:lowcoder.org}
    salt: ${SECALE_DB_ENCRYPTION_SALT:lowcoder.org}
  security:
    corsAllowedDomainString: ${SECALE_CORS_DOMAINS:*}
  js-executor:
    host: ${SECALE_NODE_SERVICE_URL:http://node-service:6060}
    password: ${SECALE_NODE_SERVICE_SECRET:}
    salt: ${SECALE_NODE_SERVICE_SECRET_SALT:}
  max-query-request-size: ${SECALE_MAX_REQUEST_SIZE:20m}
  max-query-response-size: ${SECALE_MAX_REQUEST_SIZE:20m}
  max-upload-size: ${SECALE_MAX_REQUEST_SIZE:20m}
  max-query-timeout: ${SECALE_MAX_QUERY_TIMEOUT:120}
  workspace:
    mode: ${SECALE_WORKSPACE_MODE:SAAS}
  plugin-dirs:
    - ${SECALE_PLUGINS_DIR:../plugins}
  super-admin:
    username: ${SECALE_SUPERUSER_USERNAME:admin@localhost}
    password: ${SECALE_SUPERUSER_PASSWORD:}
  marketplace:
    private-mode: ${SECALE_MARKETPLACE_PRIVATE_MODE:true}
  lowcoder-public-url: ${SECALE_PUBLIC_URL:http://frontend:3000}
  notifications-email-sender: ${SECALE_EMAIL_NOTIFICATIONS_SENDER:info@localhost}
  cookie:
    max-age-in-hours: ${SECALE_COOKIE_MAX_AGE:24}
  query:
    app-snapshot-keep-duration: ${SECALE_APP_SNAPSHOT_RETENTIONTIME:30}

material:
  mongodb-grid-fs:
    bucket-name: material

springdoc:
  api-docs:
    path: /api/docs/openapi.json
  swagger-ui:
    path: /api/docs/swagger-ui
    operations-sorter: method
  paths-to-exclude: /api/v1/**

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/api/status"
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: never
      show-components: always
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    mail:
      enabled: false
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: false
